### ISSUE TITLE
How to handle Daylight Savings

### ISSUE THREAD

**Issue by jnflint** [aguinane/nem-reader#36]
My understanding is that the NEM file times are without Daylight Savings. This distorts time of day analysis when comparing across dst and non dst times. Should adjustments be incorporated into the parsing and import process or left for analysis? Also what to do about the missing/doubled up hour at the start and end of DST?

**Comment by aguinane** [comment]
My understanding is that all NEM readings are in AEST, so there are no doubled up hours or anything even in states that have DST.  I'm in Queensland so never had any problems since we don't muck around with DST.

If you wanted to handle it when charting I guess you would set the timezone as Brisbane and then convert to local timezone before charting etc and let pytz handle all the conversions for you?

**Comment by jnflint** [comment]
Thanks, I think I will do as you suggested and let pytz handle it. If I am doing TofD analysis looking at averages, minimums or maximums across DST periods, I think I will just pretend the change over day doesn't exist so I don't get an outlier when there really isn't one. It's for my personal use so I don't have to care about others use cases. Having DST distorts power use as for some loads, usage follows the sun and for others usage tracks when you get up etc, so comparisons are distorted to some extent. No DST would be simpler, but we like it down here :-)
